[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"
edition = "2018"

[dependencies]
async-stream = "0.3"
bytes = "1.0"
bytesize = "1.0"
byteorder = "1.3"
chrono = { version = "0.4", default-features = false }
chrono-humanize = "0.1"
futures-util = { version = "0.3", default-features = false }
futures-executor = { version = "0.3", default-features = false, features = ["std"] }
headers = "0.3"
hex = "0.4"
horrorshow = { version = "0.8", default-features = false, features = ["alloc"] }
http = "0.2"
http-serve = "0.3"
hyper = { version = "0.14", features = ["http1", "http2", "server", "stream", "tcp"] }
log = "0.4"
mime_guess = "2.0"
os_str_bytes = "2.4"
percent-encoding = "2.1"
pico-args = "0.3"
pretty_env_logger = "0.4"
rand = "0.8"
rayon = "1.5"
r2d2 = "0.8"
r2d2_sqlite = "0.17"
rand_core = "0.5"
rusqlite = "0.24"
scrypt = { version = "0.5" }
tar = { version = "0.4", default-features = false }
tokio = { version = "1.0", features = ["fs", "net", "rt", "rt-multi-thread", "sync"] }
url = "2.2"
walkdir = "2.3"

[features]
default = ["bundled-windows"]

bundled-sqlite = ["rusqlite/bundled"]
bundled-windows = ["rusqlite/bundled-windows"]
