[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = "0.12"
bytes = "0.5"
bytesize = "1.0"
byteorder = "1.3"
chrono = { version = "0.4", default-features = false }
chrono-humanize = "0.0.11"
futures = { version = "0.3" }
headers = "0.3"
hex = "0.4"
horrorshow = { version = "0.8", default-features = false, features = ["alloc"] }
http = "0.2"
http-serve = "0.2"
hyper = { version = "0.13", features = ["stream"] }
log = "0.4"
mime_guess = "2.0"
os_str_bytes = "2.0"
percent-encoding = "2.1"
pretty_env_logger = "0.4"
rand = "0.7"
rayon = "1.3"
r2d2 = "0.8"
r2d2_sqlite = "0.15"
rusqlite = "0.22"
scrypt = { version = "0.2", default-features = false }
structopt = "0.3"
subtle = "2.2"
tar = { version = "0.4", default-features = false }
tokio = { version = "0.2", features = ["blocking", "fs", "io-util", "rt-threaded", "stream", "sync"] }
url = "2.1"
walkdir = "2.3"

[features]
default = ["bundled-windows"]

bundled-sqlite = ["rusqlite/bundled"]
bundled-windows = ["rusqlite/bundled-windows"]

[profile.release.build-override]
opt-level = 0
