[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = "0.11"
bytes = "0.4"
bytesize = "1.0"
byteorder = "1.3"
chrono = { version = "0.4", default-features = false }
chrono-humanize = "0.0.11"
cookie = "0.12"
diesel = { version = "1.4", default-features = false, features = ["chrono", "r2d2", "sqlite"] }
futures = { version = "0.1", default-features = false, features = ["use_std"] }
headers = "0.2"
hex = "0.4"
horrorshow = { version = "0.7", default-features = false }
http = "0.1"
http-serve = "0.1"
hyper = { version = "0.12", default-features = false, features = ["runtime"] }
log = "0.4"
mime_guess = "2.0"
percent-encoding = "2.1"
pretty_env_logger = "0.3"
rand = "0.7"
rayon = "1.2"
libsqlite3-sys = "0.16"
scrypt = { version = "0.2", default-features = false }
structopt = "0.3"
subtle = "2.2"
tar = { version = "0.4", default-features = false }
time = "0.1"
tokio = "0.1"
tokio-fs = "0.1"
tokio-sync = "0.1"
tokio-threadpool = "0.1"
url = "2.1"
walkdir = "2.2"

[features]
default = ["bundled-windows"]

bundled-sqlite = ["libsqlite3-sys/bundled"]
bundled-windows = ["libsqlite3-sys/bundled-windows"]

[profile.release]
codegen-units = 1
incremental = false
lto = true
